FROM {{ image_spec("openstack-base") }}
MAINTAINER {{ maintainer }}

COPY swift_sudoers /etc/sudoers.d/swift_sudoers
{{ copy_sources("openstack/swift", "/swift") }}
{{ copy_sources("openstack/swift3", "/swift3") }}

RUN apt-get update \
    && apt-get install -y liberasurecode-dev  \
    && apt-get clean \
    && useradd --user-group --create-home --home-dir /etc/swift -G microservices swift \
    && /var/lib/microservices/venv/bin/pip install --upgrade /swift \
    && /var/lib/microservices/venv/bin/pip install --upgrade /swift3 \
    && mkdir -p /etc/swift \
    && chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/swift_sudoers \
    && chown -R swift: /etc/swift

USER swift
