FROM {{ namespace }}/openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

COPY sources.list.debian /etc/apt/sources.list.d/ceph.list
RUN apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 460F3994 \
    && apt-get update \
    && apt-get install -y --no-install-recommends radosgw \
    && apt-get clean \
    && mkdir -p /var/lib/ceph/radosgw/ceph-rgw

