FROM {{ image_spec("openstack-base") }}
MAINTAINER {{ maintainer }}

COPY {{ render('sources.list.debian.j2') }} /etc/apt/sources.list.d/ceph.list
RUN apt-key adv --recv-keys --keyserver {{ url.ceph_repository_keyserver }} \
    {{ url.ceph_repository_keyid }} \
    && apt-get update \
    && apt-get install -y --no-install-recommends radosgw \
    && apt-get clean \
    && mkdir -p /var/lib/ceph/radosgw/ceph-rgw

